#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Any

import yaml


SERVICE_ORDER = ("frontend", "database", "storage", "compute")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Terraform files from an infra.yaml config."
    )
    parser.add_argument("--config", required=True, help="Path to infra.yaml")
    parser.add_argument(
        "--modules-dir", required=True, help="Path to the Terraform modules directory"
    )
    parser.add_argument(
        "--output-dir", required=True, help="Directory to write generated Terraform files"
    )
    return parser.parse_args()


def load_config(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise ValueError("config root must be a mapping")
    return data


def format_hcl_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    raise TypeError(f"Unsupported HCL value type: {type(value).__name__}")


def render_assignments(
    assignments: list[tuple[str, str]], indent: str = "  ", sort_keys: bool = False
) -> str:
    if sort_keys:
        assignments = sorted(assignments, key=lambda item: item[0])

    width = max(len(key) for key, _ in assignments)
    return "\n".join(f"{indent}{key.ljust(width)} = {value}" for key, value in assignments)


def build_backend_tf(include_archive: bool) -> str:
    provider_assignments = [
        ("aws", '{ source = "hashicorp/aws", version = "~> 5.0" }'),
        ("random", '{ source = "hashicorp/random", version = "~> 3.0" }'),
    ]
    if include_archive:
        provider_assignments.append(
            ("archive", '{ source = "hashicorp/archive", version = "~> 2.0" }')
        )

    required_providers = render_assignments(provider_assignments, indent="    ")

    return (
        '# Generated by infra-orchestrator. Do not edit by hand.\n\n'
        'terraform {\n'
        '  required_version = ">= 1.9"\n\n'
        '  backend "s3" {}\n\n'
        '  required_providers {\n'
        f"{required_providers}\n"
        '  }\n'
        '}\n\n'
        'provider "aws" {\n'
        '  region = var.aws_region\n\n'
        '  default_tags {\n'
        '    tags = var.default_tags\n'
        '  }\n'
        '}\n'
    )


def build_variables_tf(config: dict[str, Any]) -> str:
    project = config["project"]
    project_name = project["name"]
    aws_region = project["region"]
    tags = project.get("tags", {}) or {}

    tag_assignments = [
        ('"Project"', format_hcl_value(project_name)),
        ('"ManagedBy"', '"terraform"'),
        ('"Provisioner"', '"infra-orchestrator"'),
    ]
    for key, value in tags.items():
        tag_assignments.append((format_hcl_value(key), format_hcl_value(value)))

    tags_block = render_assignments(tag_assignments, indent="    ")

    return (
        '# Generated by infra-orchestrator. Do not edit by hand.\n\n'
        'variable "aws_region" {\n'
        '  type    = string\n'
        f"  default = {format_hcl_value(aws_region)}\n"
        '}\n\n'
        'variable "project_name" {\n'
        '  type    = string\n'
        f"  default = {format_hcl_value(project_name)}\n"
        '}\n\n'
        'variable "default_tags" {\n'
        '  type = map(string)\n'
        '  default = {\n'
        f"{tags_block}\n"
        '  }\n'
        '}\n'
    )


def module_source(modules_dir: str, module_name: str) -> str:
    return format_hcl_value(os.path.abspath(os.path.join(modules_dir, module_name)))


def render_module_block(
    name: str, source: str, extra_arguments: list[tuple[str, str]]
) -> str:
    assignments = [("source", source), *extra_arguments]
    body = render_assignments(assignments, indent="  ")
    return "\n".join([f'module "{name}" {{', body, "}"])


def build_main_tf(config: dict[str, Any], modules_dir: str) -> str:
    services = config["services"]
    blocks = [
        render_module_block(
            "iam_base",
            module_source(modules_dir, "iam-base"),
            [("project_name", "var.project_name")],
        )
    ]

    if "frontend" in services:
        frontend_args = [
            ("project_name", "var.project_name"),
            ("base_role_name", "module.iam_base.role_name"),
        ]
        for key, value in services["frontend"]["config"].items():
            frontend_args.append((key, format_hcl_value(value)))
        blocks.append(
            render_module_block(
                "frontend",
                module_source(modules_dir, "frontend-s3-cloudfront"),
                frontend_args,
            )
        )

    if "database" in services:
        database_args = [
            ("project_name", "var.project_name"),
            ("base_role_name", "module.iam_base.role_name"),
        ]
        for key, value in services["database"]["config"].items():
            database_args.append((key, format_hcl_value(value)))
        blocks.append(
            render_module_block(
                "database",
                module_source(modules_dir, "database-dynamodb"),
                database_args,
            )
        )

    if "storage" in services:
        storage_args = [
            ("project_name", "var.project_name"),
            ("base_role_name", "module.iam_base.role_name"),
        ]
        for key, value in services["storage"]["config"].items():
            storage_args.append((key, format_hcl_value(value)))
        blocks.append(
            render_module_block(
                "storage",
                module_source(modules_dir, "storage-s3"),
                storage_args,
            )
        )

    if "compute" in services:
        compute_args = [
            ("project_name", "var.project_name"),
            ("base_role_arn", "module.iam_base.role_arn"),
            ("base_role_name", "module.iam_base.role_name"),
        ]
        for key, value in services["compute"]["config"].items():
            compute_args.append((key, format_hcl_value(value)))
        blocks.append(
            render_module_block(
                "compute",
                module_source(modules_dir, "compute-lambda"),
                compute_args,
            )
        )

    return "# Generated by infra-orchestrator. Do not edit by hand.\n\n" + "\n\n".join(
        blocks
    ) + "\n"


def build_outputs_tf(config: dict[str, Any]) -> str:
    services = config["services"]
    outputs = [
        (
            "project_role_arn",
            "module.iam_base.role_arn",
        )
    ]

    if "frontend" in services:
        outputs.extend(
            [
                ("cloudfront_url", "module.frontend.distribution_url"),
                ("frontend_bucket", "module.frontend.bucket_name"),
            ]
        )

    if "database" in services:
        outputs.extend(
            [
                ("dynamodb_table_name", "module.database.table_name"),
                ("dynamodb_table_arn", "module.database.table_arn"),
            ]
        )

    if "storage" in services:
        outputs.extend(
            [
                ("storage_bucket_name", "module.storage.bucket_name"),
                ("storage_bucket_arn", "module.storage.bucket_arn"),
            ]
        )

    if "compute" in services:
        outputs.extend(
            [
                ("lambda_function_name", "module.compute.function_name"),
                ("lambda_function_arn", "module.compute.function_arn"),
                ("lambda_function_url", "module.compute.function_url"),
            ]
        )

    lines = ["# Generated by infra-orchestrator. Do not edit by hand.", ""]
    for output_name, value in outputs:
        lines.extend(
            [
                f'output "{output_name}" {{',
                f"  value = {value}",
                "}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def write_file(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def main() -> None:
    args = parse_args()
    config_path = Path(args.config)
    modules_dir = os.path.abspath(args.modules_dir)
    output_dir = Path(args.output_dir)

    config = load_config(config_path)
    output_dir.mkdir(parents=True, exist_ok=True)

    include_archive = "compute" in config.get("services", {})

    write_file(output_dir / "backend.tf", build_backend_tf(include_archive))
    write_file(output_dir / "variables.tf", build_variables_tf(config))
    write_file(output_dir / "main.tf", build_main_tf(config, modules_dir))
    write_file(output_dir / "outputs.tf", build_outputs_tf(config))


if __name__ == "__main__":
    main()
